---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 24631.
--- DateTime: 2026/3/28 21:29
---

-- 1.参数列表

-- 1.1 优惠券Id
local voucherId = ARGV[1]

-- 1.2 用户Id
local userId = ARGV[2]


-- 2. 数据key

-- 2.1 库存key
local stockKey = 'seckill:stock:' .. voucherId

-- 2.2 订单key
local orderKey = 'seckill:order:' .. voucherId

-- -- 3. 时间参数
--
-- -- 3.1 抢购开始时间
--local startTime = ARGV[3]
--
-- -- 3.2 抢购结束时间
--local endTime = ARGV[4]
--
-- -- 3.3 当前时间
--local nowTime = ARGV[5]

-- 3.脚本业务

-- 判断库存是否充足
if(tonumber(redis.call('get', stockKey)) <= 0) then
    -- 库存不足返回 1
    return 1
end
-- 判断用户是否重复下单
if (1 == redis.call('sismember', orderKey, userId)) then
    -- 用户重复下单 返回 2
    return 2
end
-- -- 判断是否在下单时间内
--if ( startTime > nowTime ) then
--    -- 秒杀尚未开始
--    return 3
--end
--if ( endTime < nowTime ) then
--    -- 秒杀已经结束
--    return 4
--end

-- 库存充足且没有重复下单

--扣除库存
redis.call("incrby", stockKey, -1)

-- 保存用户
redis.call("sadd", orderKey, userId)

return 0